image:
  file: .gitpod.Dockerfile

tasks:
  # Install dependencies first.
  - init: pip install -r ./requirements.txt
    # Then run if there's config.env, otherwise prompt to configure.
    command: >
      if [[ -f config.env ]]; then
        clear && bash run
      else
        clear && echo "Please copy the config.env.sample file and edit it to continue."
      fi
